create database VOTACION1
go
USE VOTACION1
GO
/**
TABLA USUARIO (CODIGOPK,EMAIL,CLAVE,NOMBRE,P_APELLIDO, S_APELLIDO)

TABLA CANDIDATOS (CODIGOPK,NOMBRE, APELLIDO,APELLIDO2, NOMBREPARTIDO )

TABLA VOTANTES (IDCEDULA, NOMBRE,APELLIDO, APELLIDO2, EMAIL)

TABLA VOTOS (IDCANDIDATO, IDVOTANTE)

TABLA RESULTADOS (IDRESULTADOPK,IDCANDIDATOFK,TOTAL VOTOS)

REGISTROS_VOTOS (IDRESULTADOSPK,IDVOTANTE, IDCANDIDATO, FECHA)
**/

CREATE TABLE USUARIO
(
ID INT IDENTITY (1,1) PRIMARY KEY,
EMAIL VARCHAR (50) UNIQUE NOT NULL,
CLAVE VARCHAR (30) NOT NULL,
NOMBRE VARCHAR (50) DEFAULT 'N/A',
P_APELLIDO VARCHAR (50) NOT NULL,
S_APELLIDO VARCHAR (50) NULL,

)
GO



CREATE TABLE CANDIDATOS 
(ID INT IDENTITY (1,1)PRIMARY KEY,
NOMBRE VARCHAR (50) NOT NULL, 
APELLIDO VARCHAR (50) NOT NULL,
APELLIDO2 VARCHAR (50) NOT NULL,
NOMBREPARTIDO VARCHAR (50) UNIQUE NOT NULL, 
)
GO

CREATE TABLE VOTANTES 
(
IDCEDULA int primary key, 
NOMBRE VARCHAR (60) NOT NULL,
APELLIDO VARCHAR (50) NOT NULL,
APELLIDO2 VARCHAR (50) NOT NULL,
EMAIL VARCHAR (50)DEFAULT 'N/A',
)
GO





CREATE TABLE VOTOS 
(
IDCANDIDATO INT NOT NULL,  
IDVOTANTE INT NOT NULL,
constraint fkIDCANDIDATO foreign key(IDCANDIDATO) references CANDIDATOS(ID),
constraint fkIDVOTANTE foreign key(IDVOTANTE) references VOTANTES(IDCEDULA)
)
GO


CREATE TABLE RESULTADOS 
(
IDRESULTADO INT IDENTITY PRIMARY KEY,
IDCANDIDATO1 INT NOT NULL,
TOTALVOTOS INT NOT NULL,
FECHA DATETIME DEFAULT GETDATE()
constraint fkIDCANDIDATO1 foreign key(IDCANDIDATO1) references CANDIDATOS(ID)
)
GO

CREATE TABLE REGISTROS_VOTOS (
    IDRESULTADOS INT IDENTITY(1,1) PRIMARY KEY, 
    IDCANDIDATO2 INT NOT NULL,                   
    FECHA DATETIME DEFAULT GETDATE(),           
    CONSTRAINT FKIDVOTANTE FOREIGN KEY (IDVOTANTE1) REFERENCES VOTANTES(IDCEDULA),
    CONSTRAINT FKIDCANDIDATO FOREIGN KEY (IDCANDIDATO2) REFERENCES CANDIDATOS(ID) 
);


INSERT INTO USUARIO (EMAIL,CLAVE,NOMBRE, P_APELLIDO, S_APELLIDO) VALUES ('mario@tribunal.com', '123', 'Mario', 'Solis','Herrera'), ('rebeca@tribunal.com', '456', 'Rebeca', 'Castro', 'Artavia')

SELECT * FROM USUARIO
GO

INSERT INTO CANDIDATOS (NOMBRE,APELLIDO,APELLIDO2, NOMBREPARTIDO) VALUES ('Jose Maria Figueres', 'PLN'), ('Rodrigo Chaves', 'Progreso Social'), ('Rafael Angel Calderon', 'PUSC'), ('Carlos Alvarado', 'Accion Ciudadana')
SELECT * FROM CANDIDATOS
GO

SELECT EMAIL, CLAVE, NOMBRE FROM USUARIO WHERE EMAIL='mario@tribunal.com' AND CLAVE='123'
select * from USUARIO
go
SELECT * FROM USUARIO
go
SELECT IDCANDIDATO, COUNT(*) AS TotalVotos
FROM VOTOS
GROUP BY IDCANDIDATO

SELECT c.NOMBRE,c.APELLIDO,c.APELLIDO2, v.IDCANDIDATO, COUNT(*) AS TotalVotos
FROM VOTOS v
JOIN CANDIDATOS c ON v.IDCANDIDATO = c.ID
GROUP BY c.NOMBRE,c.APELLIDO,c.APELLIDO2, v.IDCANDIDATO

INSERT INTO USUARIO (EMAIL,CLAVE,NOMBRE, P_APELLIDO, S_APELLIDO) VALUES ('mario@tribunal.com', '123', 'Mario', 'Solis','Herrera'), ('rebeca@tribunal.com', '456', 'Rebeca', 'Castro', 'Artavia')

SELECT * FROM USUARIO
GO

INSERT INTO CANDIDATOS (NOMBRE,APELLIDO,APELLIDO2, NOMBREPARTIDO) VALUES ('Jose Maria', 'Figueres','', 'PLN'), ('Rodrigo', 'Chaves','', 'Progreso Social'), ('Rafael', 'Angel', 'Calderon', 'PUSC'), ('Carlos', 'Alvarado','', 'Accion Ciudadana')
SELECT * FROM CANDIDATOS
GO

SELECT EMAIL, CLAVE, NOMBRE FROM USUARIO WHERE EMAIL='mario@tribunal.com' AND CLAVE='123'
select * from USUARIO
go
SELECT * FROM USUARIO
go


SELECT * FROM VOTANTES






